### ISSUE TITLE
Linux: OpenSUSE package count

### ISSUE THREAD

**Issue by AloneER0** [Gobidev/pfetch-rs#25]
pfetch-rs only shows how many flatpaks I have installed rather than how many packages I have installed from different package managers

**Comment by AloneER0** [comment]
openSUSE Tumbleweed and original pfetch used Bedrock's package manager(pmm) to check how many packages are installed

**Comment by Gobidev** [comment]
Thank you for reporting this. I couldn't find the usage of either `pmm` or `zypper` in the original pfetch source code ([these are all package managers checked](https://github.com/dylanaraps/pfetch/blob/a906ff89680c78cec9785f3ff49ca8b272a0f96b/pfetch#L567-L592)) so it is strange that it counted them for you there. The solution seems to be to implement a zypper package count (ideally in `libmacchina`).

**Comment by Gobidev** [comment]
I just looked more into this and this issue lead me down a rabbit hole.

`libmacchina` already supports RPM package count, which is the backend used by `zypper` by interacting with its sqlite database directly. However, it turns out that RPM also supports different database formats (`bdb` and `ndb`), where `ndb` is used by OpenSUSE. It will probably be really hard to create an implementation that directly accesses this ndb file, as this is a RPM native database implementation with no libraries I could find supporting it (for more detail see https://github.com/Macchina-CLI/libmacchina/issues/154).

So to get a package count on OpenSUSE, the options are to either change the RPM backend from `ndb` to `sqlite` (has to be done by the user), work on an implementation that gets the info from the `bdb` file directly (really hard) or just invoke an `rpm` process like the original pfetch did it (really slow).

I will probably implement the last one for now to have a package count on OpenSUSE (although being really slow) that can be disabled with the `PF_FAST_PKG_COUNT` option similar to `nix`.

**Comment by Gobidev** [comment]
With version 2.6.1, openSUSE package count has gotten significantly faster, as long as the `rpm-devel` package is installed.
