### ISSUE TITLE
Logo for Oracle Linux

### ISSUE THREAD

**Issue by Minda1975** [Gobidev/pfetch-rs#28]
Hello. Thank you for your project. I have a request. Could you include in your project support for Oracle Linux?

Here is the [link](https://www.oracle.com/linux/) for official website. 

Thank you.

**Comment by Gobidev** [comment]
Yes, I will work on it soon!

**Comment by Gobidev** [comment]
This was my first try:
![image](https://github.com/Gobidev/pfetch-rs/assets/50576978/e44470df-2788-4e41-9925-f164033f0a37)

I decided to make it symmetrical, which turned out like this:
![image](https://github.com/Gobidev/pfetch-rs/assets/50576978/957795f2-9b1d-4bc0-bc2e-9d2c062d8763)

which is the current version (can be found [in the oracle_logo branch](https://github.com/Gobidev/pfetch-rs/tree/oracle_logo)).

If you like the second version I will add that one to main. Let me know what you think.

**Comment by Minda1975** [comment]
> which is the current version (can be found [in the oracle_logo branch](https://github.com/Gobidev/pfetch-rs/tree/oracle_logo)).

Hello. I think the first version is very well done. You can leave it. Thank you very much for your hard work.

**Comment by Gobidev** [comment]
> Hello. I think the second version (symmetrical) is very well done. You can leave it. Thank you very much for your hard work.

Thank you for the feedback, the logo is now available in version 2.7.0
